### PR TITLE
Find and replace

### PR DESCRIPTION
**Pull request by RajWorking**
Created a UI functionality that allows searching for words and replacing them, either one by one or all together.
The find button allows searching a word in the transcript and highlighting it.
Clear remove the highlighted found words.

### CODE REVIEW

**Comment by adamjonas** [comment]
Cool. Looks like you've got a start for this. Some feedback below:

- The replace and replace all functionality seem to be the same. I don't see a way to do individual replacements.
- The modal requires a second click on the button to disappear, you should be able to click outside of the dropdown in order for it to close
- This is fine for a first pass on the find button but immediate highlighting based on what has already been typed (like in the browser) is likely the smoother implementation of this
- once I do a replace/replace all, all the text is highlighted and I no longer can get the read-along highlighting

**Comment by RajWorking** [comment]
ACK. Will get on these.

**Comment by RajWorking** [comment]
I have fixed the above issues. Please review the commits.

**Comment by adamjonas** [comment]
I'm ok with the choices, but replacing the speaker labels is no longer possible. Is there going to be a follow-up to address updating the speaker tags?

**Comment by RajWorking** [comment]
You can update the speaker labels easily now. Currently, they have a hardcoded transcript text so I have fixed the bug in that. There is still an issue with loading transcripts directly from JSON (maybe I can pick that later on).

**Comment by adamjonas** [comment]
1. Enter key doesn't work for either button, which would be expected behavior.

2. Cannot replace a previously replaced text.

Steps to repro in video here:

https://user-images.githubusercontent.com/755825/218142452-f6a53baf-67db-41da-b97f-19803c653946.mov

**Comment by RajWorking** [comment]
Regarding 1:
Once you have typed in the "new text", you can use tab to go to the replace and replaceAll buttons. Enter will work then.
I am not sure what is expected if one presses enter just after typing the "new text"? Is it simply executing the Replace button functionality (not ReplaceAll). So basically pressing "Enter" in textfield is same as pressing "Tab Enter"

**Comment by RajWorking** [comment]
Regarding 2:
Each word is characterized by its starting time and duration. So when you replace some text with a phrase, that entire phrase is seen to be having a single start time and duration. If need be, you can _find and replace_ the entire phrase at once instead of trying to replace a part of it.
So in your video, replace "scan" with "won't scan", then maybe replace "won't scan" with "will scan".

**Comment by adamjonas** [comment]
> Is it simply executing the Replace button functionality (not ReplaceAll)

yes, this is the expected behavior similar to functionality that you might find in a google doc or a text editor.

**Comment by adamjonas** [comment]
> So in your video, replace "scan" with "won't scan", then maybe replace "won't scan" with "will scan".

This isn't possible because "new" text isn't highlighted upon replacement.

**Comment by RajWorking** [comment]
I believe that I should continue working on this functionality after the VTT transcript format has been completed. There might some changes to the JS code so I will resume working on this later

**Comment by adamjonas** [comment]
I think you should merge what you can so it can be used upstream.

**Comment by RajWorking** [comment]
I have opened a PR directly to upstream.
[#41](https://github.com/smlum/scription/pull/41)

**Comment by adamjonas** [comment]
Is this PR meant to be open though?

**Comment by RajWorking** [comment]
No, if needed I will open a new PR later on.

**Pull request closed without merging**
