### PR TITLE
Speed toggle UI

### PR DESCRIPTION
**Pull request by RajWorking**
building this on top of find and replace branch

### CODE REVIEW

**Comment by adamjonas** [comment]
This text color is unreadable. Can you darken that, please?

Screen Shot 2023-02-08 at 3 10 29 PM

**Comment by adamjonas** [comment]
Ideally these PRs would be atomic and would not be built on each other so that you aren't bottlenecked from progress based on review from an unrelated feature.

**Comment by RajWorking** [comment]
Understood. Will create atomic PRs from next time.

**Comment by adamjonas** [comment]
The default speed on the UI is 1.75x but it plays at 1x. The speed is adjusted only after another speed is selected.

Screen Shot 2023-02-16 at 10 13 47 AM

**Comment by adamjonas** [comment]
this is also worth opening upstream

**Pull request merged**
